version: "3.3"
services:

  postgresdb:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      vpcbr:
        ipv4_address: ${POSTGRES_IP}

  # keycloak:
  #   image: jboss/keycloak:${KEYCLOAK_VERSION:-latest}
  #   container_name: ${KEYCLOAK_CONTAINER_NAME}
  #   environment:
  #     - PROXY_ADDRESS_FORWARDING=true
  #     - KEYCLOAK_USER=${KEYCLOAK_USER}
  #     - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
  #     - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
  #     - DB_DATABASE=${POSTGRES_DB}
  #     - DB_USER=${POSTGRES_USER}
  #     - DB_PASSWORD=${POSTGRES_PASSWORD}
  #     - DB_ADDR=${POSTGRES_HOST}
  #   depends_on:
  #     - postgresdb
  #   links:
  #     - postgresdb
  #   networks:
  #     vpcbr:
  #       ipv4_address: ${KEYCLOAK_IP}

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - keycloak
    # links:
    #   - keycloak
    volumes:
      - "./etc/ssl:/etc/ssl"
      - "./etc/nginx/default.conf.tmpl:/etc/nginx/conf.d/default.conf.tmpl"
    environment:
        - NGINX_HOST=${NGINX_HOST}
        - KEYCLOAK_IP=${KEYCLOAK_IP}
        - BASE_PATH=${KEYCLOAK_BASE_PATH}
    command: /bin/sh -c "envsubst '$$NGINX_HOST,$$KEYCLOAK_IP,$$BASE_PATH' < /etc/nginx/conf.d/default.conf.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    restart: always
    networks:
      vpcbr:
        ipv4_address: ${NGINX_IP}

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
#         gateway: 10.10.0.1